# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
